### ISSUE TITLE
Not able to pass Jsonify dictionary to jquery

### ISSUE THREAD

**Issue by ramcharran** [oudalab/phyllo#15]
The results obtained in app.py when we run the query are of type = defaultdict(set)

in the set part of the result dict the snippets of the query are stored.

When I tried to pass the result to the jquery it is able to retrieve everything but the snippets. I do not understand how to rectify this.

The screenshot below shows the query search on the web application
![capture1](https://user-images.githubusercontent.com/22301958/39011313-b267a8fc-43d6-11e8-8383-09d5e591ef76.PNG)

The screenshot below shows that result returned after running the query does contain the snippets:
![capture2](https://user-images.githubusercontent.com/22301958/39011472-1f1022d6-43d7-11e8-8261-8ef7bc02027f.PNG)

**Comment by cegme** [comment]
You may need to turn the data into a json object before sending it. Use 
```python
import json
stringtopass = json.dumps(type)
```
